stages:
  - build

image: node:latest
cache:
  key:
    files:
      - package.json
  paths:
   - node_modules
   - yarn.lock

before_script:
  - yarn

build:
  stage: build
  script:
   - cp $CONFIG_FILE config.js
   - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js release
   - rm -r build/tmp
