---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-200
  namespace: argocd
spec:
  destination:
    namespace: pr-200
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        namespace: pr-200
        branch: vue3
        url: pr-200.nav.tum.sexy
        server:
            MEILI_MASTER_KEY: cWRrS3dqUVhRdkFEQm5VckhaQXF1WmZMT0d2Y2ZmQllnWGdKZGpKaHN2eWh6S2dQTndOeUtYa0xM
        S0dQS1lSTg==
      version: v3
    path: pr-200
    repoURL: https://github.com/TUM-Dev/navigatum.git
    targetRevision: deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - PrunePropagationPolicy=foreground
    - CreateNamespace=true
