[package]
name = "server"
version = "0.1.0"
authors = ["Markus A <ge75sig@mytum.de>"]
edition = "2018"


[dependencies]
actix-web = "3"
lazy_static = "1.4.0"
meilisearch-sdk = "0.9"
serde = "1.0.127"
serde_json = "1.0.64"
actix-cors = "0.5.4"
futures = "0.3"
