apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: new.roomfinder.tum.sexy
    labels:
        app: navigatum
    namespace: navigatum
spec:
    commonName: new.roomfinder.tum.sexy
    dnsNames:
        - new.roomfinder.tum.sexy
    secretName: new.roomfinder.tum.sexy
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer