apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: roomapi.tum.sexy
    labels:
        app: navigatum
    namespace: navigatum
spec:
    commonName: roomapi.tum.sexy
    dnsNames:
        - roomapi.tum.sexy
    secretName: roomapi.tum.sexy
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer